extends Node

var _phases

func _ready():
	var Phase = Global.Phase
	var Spawn = Global.Spawn
	var Minion = Global.Minion
	
	_phases = {1: #009 Trance
				{
				Phase.GENERATE:true,
				Phase.DURATION:64,
				Phase.CANNON_COUNT:1,
				Phase.POWER_COUNT:1,
				Phase.INITIAL_TEXT:'Move 3',
				Phase.REPLICATE_TEXT:0,
				Phase.ARENA:0,
				Phase.SCRIPT:
					[
					{Spawn.TIME:1, Spawn.MINION:Minion.TROOPER, Spawn.LANE:3}, 
					{Spawn.TIME:7, Spawn.MINION:Minion.TROOPER, Spawn.LANE:5},
					{Spawn.TIME:9, Spawn.MINION:Minion.TROOPER, Spawn.LANE:5},
					{Spawn.TIME:13, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:17, Spawn.MINION:Minion.TROOPER, Spawn.LANE:3},
					{Spawn.TIME:18, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:25, Spawn.MINION:Minion.TANK, Spawn.LANE:1},
					{Spawn.TIME:30, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:32, Spawn.MINION:Minion.TANK, Spawn.LANE:4},
					{Spawn.TIME:38, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:38, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:43, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1},
					{Spawn.TIME:50, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:54, Spawn.MINION:Minion.TANK, Spawn.LANE:3},
					{Spawn.TIME:58, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:62, Spawn.MINION:Minion.TROOPER, Spawn.LANE:5},
					]
				},
				2: #Numa Numa
				{
				Phase.GENERATE:true,
				Phase.DURATION:84,
				Phase.CANNON_COUNT:1,
				Phase.POWER_COUNT:2,
				Phase.INITIAL_TEXT:'Dvorak',
				Phase.REPLICATE_TEXT:2,
				Phase.ARENA:0,
				Phase.SCRIPT:
					[
					{Spawn.TIME:1, Spawn.MINION:Minion.TANK, Spawn.LANE:1}, 
					{Spawn.TIME:5, Spawn.MINION:Minion.TROOPER, Spawn.LANE:3},
					{Spawn.TIME:7, Spawn.MINION:Minion.TROOPER, Spawn.LANE:3},
					{Spawn.TIME:13, Spawn.MINION:Minion.TANK, Spawn.LANE:1},
					{Spawn.TIME:13, Spawn.MINION:Minion.TROOPER, Spawn.LANE:5},
					{Spawn.TIME:19, Spawn.MINION:Minion.TANK, Spawn.LANE:1},
					{Spawn.TIME:23, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:25, Spawn.MINION:Minion.TANK, Spawn.LANE:3},
					
					{Spawn.TIME:30, Spawn.MINION:Minion.TANK, Spawn.LANE:2},
					{Spawn.TIME:30, Spawn.MINION:Minion.TANK, Spawn.LANE:4},
					{Spawn.TIME:33, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1},
					{Spawn.TIME:33, Spawn.MINION:Minion.TROOPER, Spawn.LANE:5},
					{Spawn.TIME:35, Spawn.MINION:Minion.TANK, Spawn.LANE:3},
					{Spawn.TIME:40, Spawn.MINION:Minion.TROOPER, Spawn.LANE:3},
					{Spawn.TIME:44, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:50, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1},
					{Spawn.TIME:56, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1},
					{Spawn.TIME:56, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:5},
					
					{Spawn.TIME:64, Spawn.MINION:Minion.TANK, Spawn.LANE:2},
					{Spawn.TIME:64, Spawn.MINION:Minion.TANK, Spawn.LANE:4},
					{Spawn.TIME:68, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2},
					{Spawn.TIME:68, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4},
					{Spawn.TIME:76, Spawn.MINION:Minion.TANK, Spawn.LANE:1},
					{Spawn.TIME:81, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:3},
					]
				},
				3: #Call me Spaceman
				{
				Phase.GENERATE:true,
				Phase.DURATION:95,
				Phase.CANNON_COUNT:1,
				Phase.POWER_COUNT:3,
				Phase.INITIAL_TEXT:'Watt',
				Phase.REPLICATE_TEXT:3,
				Phase.ARENA:0,
				Phase.SCRIPT:
					[
					{Spawn.TIME:1, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1},
					{Spawn.TIME:7, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2},
					{Spawn.TIME:7, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4},
					{Spawn.TIME:7, Spawn.MINION:Minion.TANK, Spawn.LANE:3},
					{Spawn.TIME:10, Spawn.MINION:Minion.TANK, Spawn.LANE:4},
					{Spawn.TIME:13, Spawn.MINION:Minion.TANK, Spawn.LANE:4},
					{Spawn.TIME:15, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1},
					{Spawn.TIME:15, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:5},
					{Spawn.TIME:23, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:23, Spawn.MINION:Minion.TROOPER, Spawn.LANE:3},
					{Spawn.TIME:23, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:28, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1},
					{Spawn.TIME:29, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:5},
					{Spawn.TIME:38, Spawn.MINION:Minion.TANK, Spawn.LANE:2},
					{Spawn.TIME:38, Spawn.MINION:Minion.TANK, Spawn.LANE:4},
					{Spawn.TIME:40, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1},
					{Spawn.TIME:40, Spawn.MINION:Minion.TANK, Spawn.LANE:2},
					{Spawn.TIME:40, Spawn.MINION:Minion.TANK, Spawn.LANE:4},
					{Spawn.TIME:50, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:50, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:53, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1},
					{Spawn.TIME:53, Spawn.MINION:Minion.TROOPER, Spawn.LANE:5},
					{Spawn.TIME:58, Spawn.MINION:Minion.TROOPER, Spawn.LANE:3},
					{Spawn.TIME:60, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2},
					{Spawn.TIME:62, Spawn.MINION:Minion.TROOPER, Spawn.LANE:3},
					{Spawn.TIME:66, Spawn.MINION:Minion.TROOPER, Spawn.LANE:3},
					{Spawn.TIME:68, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4},
					{Spawn.TIME:70, Spawn.MINION:Minion.TROOPER, Spawn.LANE:3},
					{Spawn.TIME:74, Spawn.MINION:Minion.TANK, Spawn.LANE:3},
					{Spawn.TIME:78, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1},
					{Spawn.TIME:78, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:5},
					{Spawn.TIME:83, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:88, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:88, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:3},
					{Spawn.TIME:88, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					]
				},
				4: #ReDoin
				{
				Phase.GENERATE:true,
				Phase.DURATION:95,
				Phase.CANNON_COUNT:1,
				Phase.POWER_COUNT:3,
				Phase.INITIAL_TEXT:'',
				Phase.REPLICATE_TEXT:0,
				Phase.ARENA:0,
				Phase.SCRIPT:
					[
					{Spawn.TIME:1, Spawn.MINION:Minion.HACKERI, Spawn.LANE:2}, 
					{Spawn.TIME:12, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:15, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:18, Spawn.MINION:Minion.TROOPER, Spawn.LANE:5},
					{Spawn.TIME:21, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1},
					{Spawn.TIME:24, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:3},
					{Spawn.TIME:26, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:3},
					{Spawn.TIME:28, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:3},
					{Spawn.TIME:31, Spawn.MINION:Minion.TANK, Spawn.LANE:2},
					{Spawn.TIME:35, Spawn.MINION:Minion.TANK, Spawn.LANE:4},
					
					{Spawn.TIME:42, Spawn.MINION:Minion.HACKER, Spawn.LANE:3},
					{Spawn.TIME:44, Spawn.MINION:Minion.TANK, Spawn.LANE:1},
					{Spawn.TIME:44, Spawn.MINION:Minion.TANK, Spawn.LANE:5},
					{Spawn.TIME:48, Spawn.MINION:Minion.TANK, Spawn.LANE:1},
					{Spawn.TIME:48, Spawn.MINION:Minion.TANK, Spawn.LANE:5},
					{Spawn.TIME:56, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:56, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:57, Spawn.MINION:Minion.HACKER, Spawn.LANE:3},
					{Spawn.TIME:66, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:69, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:72, Spawn.MINION:Minion.HACKER, Spawn.LANE:1},
					{Spawn.TIME:75, Spawn.MINION:Minion.HACKER, Spawn.LANE:5},
					{Spawn.TIME:78, Spawn.MINION:Minion.TANK, Spawn.LANE:3},
					
					{Spawn.TIME:82, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:88, Spawn.MINION:Minion.TANK, Spawn.LANE:1},
					{Spawn.TIME:88, Spawn.MINION:Minion.TANK, Spawn.LANE:4},
					{Spawn.TIME:88, Spawn.MINION:Minion.TANK, Spawn.LANE:5},
					{Spawn.TIME:90, Spawn.MINION:Minion.HACKER, Spawn.LANE:1},
					{Spawn.TIME:92, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:3},
					]
				},
				5: #That is where she dances
				{
				Phase.GENERATE:true,
				Phase.DURATION:75,
				Phase.CANNON_COUNT:2,
				Phase.POWER_COUNT:3,
				Phase.INITIAL_TEXT:'Tab',
				Phase.REPLICATE_TEXT:3,
				Phase.ARENA:0,
				Phase.SCRIPT:
					[
					{Spawn.TIME:1, Spawn.MINION:Minion.TANK, Spawn.LANE:2}, 
					{Spawn.TIME:8, Spawn.MINION:Minion.TANK, Spawn.LANE:2},
					{Spawn.TIME:10, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1}, 
					{Spawn.TIME:12, Spawn.MINION:Minion.TANK, Spawn.LANE:2}, 
					{Spawn.TIME:16, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1}, 
					{Spawn.TIME:22, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4}, 
					{Spawn.TIME:22, Spawn.MINION:Minion.TANK, Spawn.LANE:2}, 
					{Spawn.TIME:26, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4}, 
					{Spawn.TIME:28, Spawn.MINION:Minion.HACKER, Spawn.LANE:2},
					
					{Spawn.TIME:33, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4},
					{Spawn.TIME:35, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2},
					{Spawn.TIME:37, Spawn.MINION:Minion.TANK, Spawn.LANE:5},
					{Spawn.TIME:40, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:41, Spawn.MINION:Minion.TANK, Spawn.LANE:1},
					{Spawn.TIME:43, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:45, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:50, Spawn.MINION:Minion.HACKER, Spawn.LANE:2},
					{Spawn.TIME:52, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1}, 
					{Spawn.TIME:53, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:55, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:55, Spawn.MINION:Minion.TANK, Spawn.LANE:3},
					{Spawn.TIME:57, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:60, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2},
					{Spawn.TIME:61, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:3},
					{Spawn.TIME:62, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4},
					{Spawn.TIME:72, Spawn.MINION:Minion.HACKER, Spawn.LANE:2},
					{Spawn.TIME:72, Spawn.MINION:Minion.HACKER, Spawn.LANE:4},
					]
				},
				6: # Altador Cup
				{
				Phase.GENERATE:true,
				Phase.DURATION:141,
				Phase.CANNON_COUNT:2,
				Phase.POWER_COUNT:4,
				Phase.INITIAL_TEXT:'Net',
				Phase.REPLICATE_TEXT:4,
				Phase.ARENA:0,
				Phase.SCRIPT:
					[
					{Spawn.TIME:1, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2}, 
					{Spawn.TIME:2, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1}, 
					{Spawn.TIME:2, Spawn.MINION:Minion.TROOPER, Spawn.LANE:3},
					{Spawn.TIME:3, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2},
					{Spawn.TIME:7, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4},
					{Spawn.TIME:7, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:6},
					{Spawn.TIME:8, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4},
					{Spawn.TIME:8, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:6},
					{Spawn.TIME:9, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4},
					{Spawn.TIME:9, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:6},
					{Spawn.TIME:10, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4},
					{Spawn.TIME:10, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:6},
					
					{Spawn.TIME:12, Spawn.MINION:Minion.TANK, Spawn.LANE:1},
					{Spawn.TIME:14, Spawn.MINION:Minion.TANK, Spawn.LANE:5},
					{Spawn.TIME:14, Spawn.MINION:Minion.TANK, Spawn.LANE:2},
					{Spawn.TIME:16, Spawn.MINION:Minion.TANK, Spawn.LANE:0},
					{Spawn.TIME:20, Spawn.MINION:Minion.TROOPER, Spawn.LANE:5},
					{Spawn.TIME:24, Spawn.MINION:Minion.TROOPER, Spawn.LANE:3},
					{Spawn.TIME:25, Spawn.MINION:Minion.TROOPER, Spawn.LANE:0},
					{Spawn.TIME:26, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:34, Spawn.MINION:Minion.HACKER, Spawn.LANE:0},
					{Spawn.TIME:39, Spawn.MINION:Minion.HACKER, Spawn.LANE:2},
					{Spawn.TIME:46, Spawn.MINION:Minion.HACKER, Spawn.LANE:4},
					{Spawn.TIME:52, Spawn.MINION:Minion.HACKER, Spawn.LANE:6},
					
					{Spawn.TIME:58, Spawn.MINION:Minion.TROOPER, Spawn.LANE:3},
					{Spawn.TIME:59, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:60, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:62, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1},
					{Spawn.TIME:64, Spawn.MINION:Minion.TROOPER, Spawn.LANE:5},
					{Spawn.TIME:66, Spawn.MINION:Minion.TROOPER, Spawn.LANE:0},
					{Spawn.TIME:68, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:6},
					{Spawn.TIME:72, Spawn.MINION:Minion.TANK, Spawn.LANE:6},
					{Spawn.TIME:74, Spawn.MINION:Minion.TANK, Spawn.LANE:0},
					{Spawn.TIME:77, Spawn.MINION:Minion.TANK, Spawn.LANE:4},
					{Spawn.TIME:80, Spawn.MINION:Minion.TANK, Spawn.LANE:2},
					{Spawn.TIME:84, Spawn.MINION:Minion.TANK, Spawn.LANE:0},
					{Spawn.TIME:87, Spawn.MINION:Minion.TANK, Spawn.LANE:6},
					{Spawn.TIME:91, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4},
					{Spawn.TIME:92, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4},
					{Spawn.TIME:93, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2},
					{Spawn.TIME:94, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2},
					
					{Spawn.TIME:103, Spawn.MINION:Minion.TROOPER, Spawn.LANE:0},
					{Spawn.TIME:105, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:107, Spawn.MINION:Minion.TROOPER, Spawn.LANE:6},
					{Spawn.TIME:109, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:111, Spawn.MINION:Minion.TROOPER, Spawn.LANE:3},
					{Spawn.TIME:113, Spawn.MINION:Minion.TROOPER, Spawn.LANE:5},
					
					{Spawn.TIME:118, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:0},
					{Spawn.TIME:120, Spawn.MINION:Minion.TANK, Spawn.LANE:4},
					{Spawn.TIME:122, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:6},
					{Spawn.TIME:124, Spawn.MINION:Minion.TANK, Spawn.LANE:2},
					{Spawn.TIME:126, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:3},
					{Spawn.TIME:128, Spawn.MINION:Minion.TANK, Spawn.LANE:5},
					{Spawn.TIME:130, Spawn.MINION:Minion.HACKER, Spawn.LANE:0},
					{Spawn.TIME:132, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:134, Spawn.MINION:Minion.TANK, Spawn.LANE:6},
					{Spawn.TIME:136, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:138, Spawn.MINION:Minion.TANK, Spawn.LANE:3},
					{Spawn.TIME:140, Spawn.MINION:Minion.HACKER, Spawn.LANE:5},
					]
				},
				7: # Red Arena
				{
				Phase.GENERATE:true,
				Phase.DURATION:84,
				Phase.CANNON_COUNT:2,
				Phase.POWER_COUNT:4,
				Phase.INITIAL_TEXT:'>',
				Phase.REPLICATE_TEXT:0,
				Phase.ARENA:1,
				Phase.SCRIPT:
					[
					{Spawn.TIME:1, Spawn.MINION:Minion.TANK, Spawn.LANE:2}, 
					{Spawn.TIME:1, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:2},
					{Spawn.TIME:4, Spawn.MINION:Minion.TANK, Spawn.LANE:4},
					{Spawn.TIME:4, Spawn.MINION:Minion.TANK, Spawn.LANE:6},
					{Spawn.TIME:7, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:5},
					{Spawn.TIME:9, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1},
					{Spawn.TIME:11, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:3},
					{Spawn.TIME:13, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:5},
					{Spawn.TIME:13, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:1},
					
					{Spawn.TIME:16, Spawn.MINION:Minion.TANK, Spawn.LANE:0},
					{Spawn.TIME:16, Spawn.MINION:Minion.TANK, Spawn.LANE:6},
					{Spawn.TIME:19, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:2},
					{Spawn.TIME:19, Spawn.MINION:Minion.HACKER, Spawn.LANE:3},
					{Spawn.TIME:19, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:4},
					
					{Spawn.TIME:25, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:3},
					{Spawn.TIME:27, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1},
					{Spawn.TIME:27, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:5},
					{Spawn.TIME:31, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:0},
					
					{Spawn.TIME:37, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:1},
					{Spawn.TIME:38, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:3},
					{Spawn.TIME:39, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:5},
					{Spawn.TIME:43, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:4},
					{Spawn.TIME:44, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:2},
					
					{Spawn.TIME:46, Spawn.MINION:Minion.TROOPER, Spawn.LANE:0}, 
					{Spawn.TIME:46, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2}, 
					{Spawn.TIME:46, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4}, 
					{Spawn.TIME:46, Spawn.MINION:Minion.TROOPER, Spawn.LANE:6}, 
					{Spawn.TIME:49, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:1},
					{Spawn.TIME:49, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:3},
					{Spawn.TIME:49, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:5},
					
					{Spawn.TIME:54, Spawn.MINION:Minion.TANK, Spawn.LANE:0},
					{Spawn.TIME:54, Spawn.MINION:Minion.TANK, Spawn.LANE:6},
					{Spawn.TIME:54, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:0},
					{Spawn.TIME:57, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1},
					{Spawn.TIME:57, Spawn.MINION:Minion.TROOPER, Spawn.LANE:5},
					{Spawn.TIME:57, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:1},
					{Spawn.TIME:60, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2},
					{Spawn.TIME:60, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4},
					{Spawn.TIME:60, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:2},
					{Spawn.TIME:63, Spawn.MINION:Minion.HACKER, Spawn.LANE:3},
					{Spawn.TIME:63, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:3},
					{Spawn.TIME:66, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2},
					{Spawn.TIME:66, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4},
					{Spawn.TIME:66, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:4},
					{Spawn.TIME:69, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1},
					{Spawn.TIME:69, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:5},
					{Spawn.TIME:69, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:5},
					{Spawn.TIME:72, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:0},
					{Spawn.TIME:72, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:6},
					{Spawn.TIME:72, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:6},
					
					#{Spawn.TIME:77, Spawn.MINION:Minion.HACKER, Spawn.LANE:0},
					#{Spawn.TIME:77, Spawn.MINION:Minion.HACKER, Spawn.LANE:6},
					{Spawn.TIME:76, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:1},
					{Spawn.TIME:77, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:2},
					{Spawn.TIME:78, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:3},
					{Spawn.TIME:79, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:4},
					{Spawn.TIME:80, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:5},
					]
				},
				8: #WAR! Gr1z Forever
				{
				Phase.GENERATE:true,
				Phase.DURATION:122,
				Phase.CANNON_COUNT:2,
				Phase.POWER_COUNT:5,
				Phase.INITIAL_TEXT:'Internet',
				Phase.REPLICATE_TEXT:5,
				Phase.ARENA:0,
				Phase.SCRIPT:
					[
					{Spawn.TIME:1, Spawn.MINION:Minion.TANK, Spawn.LANE:0}, 
					{Spawn.TIME:1, Spawn.MINION:Minion.TANK, Spawn.LANE:2},
					{Spawn.TIME:1, Spawn.MINION:Minion.TANK, Spawn.LANE:4},
					{Spawn.TIME:1, Spawn.MINION:Minion.TANK, Spawn.LANE:6},
					{Spawn.TIME:4, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1}, 
					{Spawn.TIME:4, Spawn.MINION:Minion.TROOPER, Spawn.LANE:3},
					{Spawn.TIME:4, Spawn.MINION:Minion.TROOPER, Spawn.LANE:5},
					{Spawn.TIME:9, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:6},
					{Spawn.TIME:10, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4},
					{Spawn.TIME:11, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2},
					
					{Spawn.TIME:15, Spawn.MINION:Minion.TANK, Spawn.LANE:2},
					{Spawn.TIME:15, Spawn.MINION:Minion.TANK, Spawn.LANE:4},
					{Spawn.TIME:19, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1}, 
					{Spawn.TIME:19, Spawn.MINION:Minion.TROOPER, Spawn.LANE:3},
					{Spawn.TIME:19, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:5},
					{Spawn.TIME:22, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1},
					{Spawn.TIME:26, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:30, Spawn.MINION:Minion.TROOPER, Spawn.LANE:5},
					{Spawn.TIME:33, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1},
					{Spawn.TIME:36, Spawn.MINION:Minion.TROOPER, Spawn.LANE:5},
					{Spawn.TIME:40, Spawn.MINION:Minion.BOMBER, Spawn.LANE:3},
					{Spawn.TIME:46, Spawn.MINION:Minion.BOMBER, Spawn.LANE:2},
					{Spawn.TIME:46, Spawn.MINION:Minion.BOMBER, Spawn.LANE:4},
					{Spawn.TIME:47, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:47, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:52, Spawn.MINION:Minion.HACKER, Spawn.LANE:0},
					{Spawn.TIME:53, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:6},
					{Spawn.TIME:60, Spawn.MINION:Minion.HACKER, Spawn.LANE:1},
					{Spawn.TIME:61, Spawn.MINION:Minion.BOMBER, Spawn.LANE:0},
					
					{Spawn.TIME:68, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:68, Spawn.MINION:Minion.TROOPER, Spawn.LANE:3},
					{Spawn.TIME:68, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:75, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:0},
					{Spawn.TIME:75, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1},
					{Spawn.TIME:75, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:5},
					{Spawn.TIME:75, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:6},
					{Spawn.TIME:81, Spawn.MINION:Minion.TANK, Spawn.LANE:1},
					{Spawn.TIME:81, Spawn.MINION:Minion.TANK, Spawn.LANE:3},
					{Spawn.TIME:81, Spawn.MINION:Minion.TANK, Spawn.LANE:5},
					{Spawn.TIME:87, Spawn.MINION:Minion.BOMBER, Spawn.LANE:0},
					{Spawn.TIME:87, Spawn.MINION:Minion.BOMBER, Spawn.LANE:2},
					{Spawn.TIME:87, Spawn.MINION:Minion.BOMBER, Spawn.LANE:4},
					{Spawn.TIME:87, Spawn.MINION:Minion.BOMBER, Spawn.LANE:6},
					
					{Spawn.TIME:91, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:0},
					{Spawn.TIME:91, Spawn.MINION:Minion.BOMBER, Spawn.LANE:1},
					{Spawn.TIME:91, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:91, Spawn.MINION:Minion.TANK, Spawn.LANE:3},
					{Spawn.TIME:91, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:91, Spawn.MINION:Minion.BOMBER, Spawn.LANE:5},
					{Spawn.TIME:91, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:6},
					
					{Spawn.TIME:108, Spawn.MINION:Minion.BOMBER, Spawn.LANE:0},
					{Spawn.TIME:108, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1},
					{Spawn.TIME:108, Spawn.MINION:Minion.BOMBER, Spawn.LANE:2},
					{Spawn.TIME:108, Spawn.MINION:Minion.TROOPER, Spawn.LANE:3},
					{Spawn.TIME:108, Spawn.MINION:Minion.BOMBER, Spawn.LANE:4},
					{Spawn.TIME:108, Spawn.MINION:Minion.TROOPER, Spawn.LANE:5},
					{Spawn.TIME:108, Spawn.MINION:Minion.BOMBER, Spawn.LANE:6},
					{Spawn.TIME:109, Spawn.MINION:Minion.BOMBER, Spawn.LANE:1},
					{Spawn.TIME:109, Spawn.MINION:Minion.BOMBER, Spawn.LANE:3},
					{Spawn.TIME:109, Spawn.MINION:Minion.BOMBER, Spawn.LANE:5},
					
					{Spawn.TIME:112, Spawn.MINION:Minion.BOMBER, Spawn.LANE:2},
					{Spawn.TIME:113, Spawn.MINION:Minion.BOMBER, Spawn.LANE:3},
					{Spawn.TIME:115, Spawn.MINION:Minion.BOMBER, Spawn.LANE:5},
					{Spawn.TIME:116, Spawn.MINION:Minion.BOMBER, Spawn.LANE:4},
					{Spawn.TIME:119, Spawn.MINION:Minion.BOMBER, Spawn.LANE:3},
					{Spawn.TIME:120, Spawn.MINION:Minion.BOMBER, Spawn.LANE:2},
					{Spawn.TIME:120, Spawn.MINION:Minion.BOMBER, Spawn.LANE:4},
					{Spawn.TIME:121, Spawn.MINION:Minion.BOMBER, Spawn.LANE:1},
					{Spawn.TIME:121, Spawn.MINION:Minion.BOMBER, Spawn.LANE:5},
					{Spawn.TIME:122, Spawn.MINION:Minion.BOMBER, Spawn.LANE:0},
					{Spawn.TIME:122, Spawn.MINION:Minion.BOMBER, Spawn.LANE:6},
					]
				},
				9: # Surprise Buttsecks Instrumental
				{
				Phase.GENERATE:true,
				Phase.DURATION:112,
				Phase.CANNON_COUNT:2,
				Phase.POWER_COUNT:5,
				Phase.INITIAL_TEXT:'Watt',
				Phase.REPLICATE_TEXT:3,
				Phase.ARENA:1,
				Phase.SCRIPT:
					[ 
					{Spawn.TIME:1, Spawn.MINION:Minion.SLICK, Spawn.LANE:2},
					{Spawn.TIME:5, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1},
					{Spawn.TIME:5, Spawn.MINION:Minion.SLICK, Spawn.LANE:5},
					{Spawn.TIME:5, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:6},
					{Spawn.TIME:11, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1}, 
					{Spawn.TIME:12, Spawn.MINION:Minion.BOMBER, Spawn.LANE:3}, 
					{Spawn.TIME:14, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4},
					{Spawn.TIME:20, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:0},
					{Spawn.TIME:20, Spawn.MINION:Minion.TANK, Spawn.LANE:5},
					{Spawn.TIME:20, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:6},
					{Spawn.TIME:21, Spawn.MINION:Minion.TANK, Spawn.LANE:1},
					{Spawn.TIME:22, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:3},
					{Spawn.TIME:27, Spawn.MINION:Minion.SLICK, Spawn.LANE:2},
					{Spawn.TIME:28, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:2},
					
					{Spawn.TIME:35, Spawn.MINION:Minion.SLICK, Spawn.LANE:0},
					{Spawn.TIME:36, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:3},
					{Spawn.TIME:37, Spawn.MINION:Minion.SLICK, Spawn.LANE:6},
					{Spawn.TIME:46, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:0},
					{Spawn.TIME:46, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2},
					{Spawn.TIME:47, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:6},
					{Spawn.TIME:47, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4},
					{Spawn.TIME:48, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1},
					{Spawn.TIME:49, Spawn.MINION:Minion.TROOPER, Spawn.LANE:5},
					{Spawn.TIME:51, Spawn.MINION:Minion.TANK, Spawn.LANE:0},
					{Spawn.TIME:54, Spawn.MINION:Minion.TANK, Spawn.LANE:6},
					{Spawn.TIME:54, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:3},
					
					{Spawn.TIME:60, Spawn.MINION:Minion.HACKER, Spawn.LANE:3},
					{Spawn.TIME:60, Spawn.MINION:Minion.BOMBER, Spawn.LANE:1},
					{Spawn.TIME:60, Spawn.MINION:Minion.BOMBER, Spawn.LANE:5},
					{Spawn.TIME:60, Spawn.MINION:Minion.SLICK, Spawn.LANE:2},
					{Spawn.TIME:60, Spawn.MINION:Minion.SLICK, Spawn.LANE:4},
					{Spawn.TIME:60, Spawn.MINION:Minion.SLICK, Spawn.LANE:0},
					{Spawn.TIME:60, Spawn.MINION:Minion.SLICK, Spawn.LANE:6},
					{Spawn.TIME:61, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:1},
					{Spawn.TIME:63, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:5},
					
					{Spawn.TIME:70, Spawn.MINION:Minion.TROOPER, Spawn.LANE:0},
					{Spawn.TIME:70, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:70, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:70, Spawn.MINION:Minion.TROOPER, Spawn.LANE:6},
					
					{Spawn.TIME:73, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:1},
					{Spawn.TIME:77, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:2},
					
					{Spawn.TIME:80, Spawn.MINION:Minion.SLICK, Spawn.LANE:0},
					{Spawn.TIME:80, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:80, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:80, Spawn.MINION:Minion.SLICK, Spawn.LANE:6},
					
					{Spawn.TIME:82, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:5},
					{Spawn.TIME:85, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:4},
					{Spawn.TIME:89, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:0},
					
					{Spawn.TIME:90, Spawn.MINION:Minion.SLICK, Spawn.LANE:0},
					{Spawn.TIME:90, Spawn.MINION:Minion.SLICK, Spawn.LANE:2},
					{Spawn.TIME:90, Spawn.MINION:Minion.SLICK, Spawn.LANE:4},
					{Spawn.TIME:90, Spawn.MINION:Minion.SLICK, Spawn.LANE:6},
					
					{Spawn.TIME:92, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:6},
					{Spawn.TIME:96, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:3},
					
					{Spawn.TIME:100, Spawn.MINION:Minion.SLICK, Spawn.LANE:0},
					{Spawn.TIME:101, Spawn.MINION:Minion.BOMBER, Spawn.LANE:1},
					{Spawn.TIME:102, Spawn.MINION:Minion.SLICK, Spawn.LANE:2},
					{Spawn.TIME:103, Spawn.MINION:Minion.BOMBER, Spawn.LANE:3},
					{Spawn.TIME:104, Spawn.MINION:Minion.SLICK, Spawn.LANE:4},
					{Spawn.TIME:105, Spawn.MINION:Minion.BOMBER, Spawn.LANE:5},
					{Spawn.TIME:106, Spawn.MINION:Minion.SLICK, Spawn.LANE:6},
					
					]
				},
				10: # Heavy's Pizza Song Instrumental
				{
				Phase.GENERATE:true,
				Phase.DURATION:98,
				Phase.CANNON_COUNT:2,
				Phase.POWER_COUNT:6,
				Phase.INITIAL_TEXT:'Kaboom',
				Phase.REPLICATE_TEXT:6,
				Phase.ARENA:1,
				Phase.SCRIPT:
					[
					{Spawn.TIME:1, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1}, 
					{Spawn.TIME:1, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2}, 
					{Spawn.TIME:1, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:3}, 
					{Spawn.TIME:2, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1}, 
					{Spawn.TIME:2, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2}, 
					{Spawn.TIME:2, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:3}, 
					{Spawn.TIME:3, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1}, 
					{Spawn.TIME:3, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2}, 
					{Spawn.TIME:3, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:3}, 
					{Spawn.TIME:10, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:3},
					{Spawn.TIME:10, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4}, 
					{Spawn.TIME:10, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:5}, 
					{Spawn.TIME:10, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:6}, 
					{Spawn.TIME:11, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4}, 
					{Spawn.TIME:11, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:5}, 
					{Spawn.TIME:11, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:6}, 
					{Spawn.TIME:12, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4}, 
					{Spawn.TIME:12, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:5}, 
					{Spawn.TIME:12, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:6}, 
					{Spawn.TIME:12, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1}, 
					{Spawn.TIME:12, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2}, 
					{Spawn.TIME:12, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:0}, 
					{Spawn.TIME:13, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1}, 
					{Spawn.TIME:13, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2}, 
					{Spawn.TIME:13, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:0}, 
					{Spawn.TIME:13, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1}, 
					{Spawn.TIME:13, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2}, 
					{Spawn.TIME:13, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:0}, 
					{Spawn.TIME:15, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:3},
					{Spawn.TIME:21, Spawn.MINION:Minion.SLICK, Spawn.LANE:3},
					{Spawn.TIME:24, Spawn.MINION:Minion.TANK, Spawn.LANE:2},
					{Spawn.TIME:25, Spawn.MINION:Minion.TROOPER, Spawn.LANE:3},
					{Spawn.TIME:26, Spawn.MINION:Minion.TANK, Spawn.LANE:4},
					
					{Spawn.TIME:32, Spawn.MINION:Minion.TANK, Spawn.LANE:1},
					{Spawn.TIME:32, Spawn.MINION:Minion.TANK, Spawn.LANE:3},
					{Spawn.TIME:32, Spawn.MINION:Minion.TANK, Spawn.LANE:5},
					{Spawn.TIME:34, Spawn.MINION:Minion.TANK, Spawn.LANE:0},
					{Spawn.TIME:34, Spawn.MINION:Minion.TANK, Spawn.LANE:2},
					{Spawn.TIME:34, Spawn.MINION:Minion.TANK, Spawn.LANE:4},
					{Spawn.TIME:34, Spawn.MINION:Minion.TANK, Spawn.LANE:6},
					{Spawn.TIME:34, Spawn.MINION:Minion.HACKER, Spawn.LANE:3},
					{Spawn.TIME:34, Spawn.MINION:Minion.TANK, Spawn.LANE:0},
					{Spawn.TIME:34, Spawn.MINION:Minion.TANK, Spawn.LANE:5},
					{Spawn.TIME:37, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:3},
					{Spawn.TIME:37, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2},
					{Spawn.TIME:37, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4},
					{Spawn.TIME:44, Spawn.MINION:Minion.SLICK, Spawn.LANE:2},
					{Spawn.TIME:45, Spawn.MINION:Minion.SLICK, Spawn.LANE:4},
					{Spawn.TIME:46, Spawn.MINION:Minion.SLICK, Spawn.LANE:3},
					{Spawn.TIME:47, Spawn.MINION:Minion.SLICK, Spawn.LANE:5},
					
					{Spawn.TIME:55, Spawn.MINION:Minion.HACKER, Spawn.LANE:1},
					{Spawn.TIME:59, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:2},
					{Spawn.TIME:62, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:3},
					{Spawn.TIME:63, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:3},
					{Spawn.TIME:66, Spawn.MINION:Minion.HACKER, Spawn.LANE:5},
					{Spawn.TIME:67, Spawn.MINION:Minion.REDBLAST, Spawn.LANE:4},
					{Spawn.TIME:71, Spawn.MINION:Minion.TANK, Spawn.LANE:2},
					{Spawn.TIME:71, Spawn.MINION:Minion.TANK, Spawn.LANE:3},
					{Spawn.TIME:71, Spawn.MINION:Minion.TANK, Spawn.LANE:4},
					
					{Spawn.TIME:76, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1},
					{Spawn.TIME:76, Spawn.MINION:Minion.TANK, Spawn.LANE:2},
					{Spawn.TIME:76, Spawn.MINION:Minion.BOMBER, Spawn.LANE:3},
					{Spawn.TIME:76, Spawn.MINION:Minion.TANK, Spawn.LANE:4},
					{Spawn.TIME:76, Spawn.MINION:Minion.TROOPER, Spawn.LANE:5},
					
					{Spawn.TIME:81, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2}, 
					{Spawn.TIME:81, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:3}, 
					{Spawn.TIME:81, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4}, 
					{Spawn.TIME:82, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2}, 
					{Spawn.TIME:82, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:3}, 
					{Spawn.TIME:82, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4}, 
					
					{Spawn.TIME:89, Spawn.MINION:Minion.SLICK, Spawn.LANE:1},
					{Spawn.TIME:89, Spawn.MINION:Minion.BOMBER, Spawn.LANE:2},
					{Spawn.TIME:89, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:3},
					{Spawn.TIME:89, Spawn.MINION:Minion.BOMBER, Spawn.LANE:4},
					{Spawn.TIME:89, Spawn.MINION:Minion.SLICK, Spawn.LANE:5},
					]
				},
				11: # Dreamworld
				{
				Phase.GENERATE:true,
				Phase.DURATION:100,
				Phase.CANNON_COUNT:2,
				Phase.POWER_COUNT:6,
				Phase.INITIAL_TEXT:'Move 5',
				Phase.REPLICATE_TEXT:0,
				Phase.ARENA:2,
				Phase.SCRIPT:
					[
					{Spawn.TIME:1, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:5}, 
					{Spawn.TIME:2, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:5}, 
					{Spawn.TIME:4, Spawn.MINION:Minion.VIOLETBLAST, Spawn.LANE:3}, 
					{Spawn.TIME:5, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1}, 
					{Spawn.TIME:6, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1}, 
					{Spawn.TIME:8, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2}, 
					{Spawn.TIME:8, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4}, 
					{Spawn.TIME:13, Spawn.MINION:Minion.TANK, Spawn.LANE:4}, 
					{Spawn.TIME:13, Spawn.MINION:Minion.HACKER, Spawn.LANE:6}, 
					{Spawn.TIME:17, Spawn.MINION:Minion.TANK, Spawn.LANE:4}, 
					{Spawn.TIME:20, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1}, 
					{Spawn.TIME:20, Spawn.MINION:Minion.TROOPER, Spawn.LANE:5}, 
					{Spawn.TIME:25, Spawn.MINION:Minion.BOMBER, Spawn.LANE:3}, 
					{Spawn.TIME:25, Spawn.MINION:Minion.TANK, Spawn.LANE:4}, 
					{Spawn.TIME:27, Spawn.MINION:Minion.TANK, Spawn.LANE:5}, 
					{Spawn.TIME:27, Spawn.MINION:Minion.TANK, Spawn.LANE:4}, 
					{Spawn.TIME:32, Spawn.MINION:Minion.HACKER, Spawn.LANE:0}, 
					{Spawn.TIME:32, Spawn.MINION:Minion.SLICK, Spawn.LANE:3}, 
					{Spawn.TIME:32, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4}, 
					{Spawn.TIME:32, Spawn.MINION:Minion.TROOPER, Spawn.LANE:5}, 
					{Spawn.TIME:32, Spawn.MINION:Minion.TROOPER, Spawn.LANE:6}, 
					{Spawn.TIME:40, Spawn.MINION:Minion.TROOPER, Spawn.LANE:3}, 
					{Spawn.TIME:46, Spawn.MINION:Minion.SLICK, Spawn.LANE:1}, 
					{Spawn.TIME:46, Spawn.MINION:Minion.TROOPER, Spawn.LANE:6}, 
					{Spawn.TIME:49, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:0}, 
					{Spawn.TIME:54, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4}, 
					{Spawn.TIME:55, Spawn.MINION:Minion.TROOPER, Spawn.LANE:6},
					{Spawn.TIME:56, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					
					{Spawn.TIME:61, Spawn.MINION:Minion.BOMBER, Spawn.LANE:0},
					{Spawn.TIME:61, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2},
					{Spawn.TIME:61, Spawn.MINION:Minion.BOMBER, Spawn.LANE:4},
					{Spawn.TIME:61, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:6},
					{Spawn.TIME:63, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1},
					{Spawn.TIME:63, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:3},
					{Spawn.TIME:63, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:5},
					
					{Spawn.TIME:67, Spawn.MINION:Minion.TANK, Spawn.LANE:0},
					{Spawn.TIME:67, Spawn.MINION:Minion.TANK, Spawn.LANE:3},
					{Spawn.TIME:71, Spawn.MINION:Minion.TANK, Spawn.LANE:1},
					{Spawn.TIME:71, Spawn.MINION:Minion.TANK, Spawn.LANE:4},
					{Spawn.TIME:75, Spawn.MINION:Minion.TANK, Spawn.LANE:2},
					{Spawn.TIME:75, Spawn.MINION:Minion.TANK, Spawn.LANE:6},
					{Spawn.TIME:79, Spawn.MINION:Minion.BOMBER, Spawn.LANE:3},
					{Spawn.TIME:79, Spawn.MINION:Minion.SLICK, Spawn.LANE:6},
					
					{Spawn.TIME:91, Spawn.MINION:Minion.HACKER, Spawn.LANE:3},
					{Spawn.TIME:91, Spawn.MINION:Minion.BOMBER, Spawn.LANE:2},
					{Spawn.TIME:91, Spawn.MINION:Minion.BOMBER, Spawn.LANE:4},
					{Spawn.TIME:91, Spawn.MINION:Minion.TANK, Spawn.LANE:1},
					{Spawn.TIME:91, Spawn.MINION:Minion.TANK, Spawn.LANE:5},
					{Spawn.TIME:91, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:0},
					{Spawn.TIME:91, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:6},
					
					]
				},
				12: # Leek spin remix
				{
				Phase.GENERATE:true,
				Phase.DURATION:120,
				Phase.CANNON_COUNT:3,
				Phase.POWER_COUNT:6,
				Phase.INITIAL_TEXT:'Shift',
				Phase.REPLICATE_TEXT:1,
				Phase.ARENA:2,
				Phase.SCRIPT:
					[
					{Spawn.TIME:1, Spawn.MINION:Minion.HACKER, Spawn.LANE:4}, 
					{Spawn.TIME:2, Spawn.MINION:Minion.VIOLETBLAST, Spawn.LANE:3}, 
					{Spawn.TIME:4, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2},
					{Spawn.TIME:8, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1},
					{Spawn.TIME:10, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:12, Spawn.MINION:Minion.TANK, Spawn.LANE:1},
					{Spawn.TIME:14, Spawn.MINION:Minion.TANK, Spawn.LANE:2},
					{Spawn.TIME:16, Spawn.MINION:Minion.TANK, Spawn.LANE:1},
					{Spawn.TIME:18, Spawn.MINION:Minion.TANK, Spawn.LANE:3},
					{Spawn.TIME:26, Spawn.MINION:Minion.TANK, Spawn.LANE:1},
					{Spawn.TIME:26, Spawn.MINION:Minion.TANK, Spawn.LANE:2},
					{Spawn.TIME:26, Spawn.MINION:Minion.TANK, Spawn.LANE:4},
					{Spawn.TIME:31, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:5},
					{Spawn.TIME:33, Spawn.MINION:Minion.SLICK, Spawn.LANE:1},
					{Spawn.TIME:37, Spawn.MINION:Minion.TANK, Spawn.LANE:2},
					{Spawn.TIME:39, Spawn.MINION:Minion.TANK, Spawn.LANE:4},
					{Spawn.TIME:43, Spawn.MINION:Minion.BOMBER, Spawn.LANE:2},
					{Spawn.TIME:43, Spawn.MINION:Minion.BOMBER, Spawn.LANE:3},
					{Spawn.TIME:43, Spawn.MINION:Minion.BOMBER, Spawn.LANE:4},
					{Spawn.TIME:47, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1},
					{Spawn.TIME:47, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:5},
					{Spawn.TIME:49, Spawn.MINION:Minion.SLICK, Spawn.LANE:0},
					{Spawn.TIME:50, Spawn.MINION:Minion.SLICK, Spawn.LANE:6},
					{Spawn.TIME:56, Spawn.MINION:Minion.HACKER, Spawn.LANE:4},
					{Spawn.TIME:61, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1},
					{Spawn.TIME:62, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:63, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:65, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:66, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:67, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1},
					{Spawn.TIME:75, Spawn.MINION:Minion.SLICK, Spawn.LANE:1},
					{Spawn.TIME:76, Spawn.MINION:Minion.SLICK, Spawn.LANE:4},
					{Spawn.TIME:81, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:1},
					{Spawn.TIME:81, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:2},
					{Spawn.TIME:81, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:3},
					{Spawn.TIME:81, Spawn.MINION:Minion.SPEEDER, Spawn.LANE:4},
					{Spawn.TIME:83, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1},
					{Spawn.TIME:85, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:87, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:88, Spawn.MINION:Minion.TROOPER, Spawn.LANE:1},
					{Spawn.TIME:89, Spawn.MINION:Minion.TROOPER, Spawn.LANE:4},
					{Spawn.TIME:90, Spawn.MINION:Minion.TROOPER, Spawn.LANE:2},
					{Spawn.TIME:93, Spawn.MINION:Minion.TANK, Spawn.LANE:0},
					{Spawn.TIME:93, Spawn.MINION:Minion.SLICK, Spawn.LANE:3},
					{Spawn.TIME:93, Spawn.MINION:Minion.TANK, Spawn.LANE:6},
					{Spawn.TIME:94, Spawn.MINION:Minion.BOMBER, Spawn.LANE:2},
					{Spawn.TIME:94, Spawn.MINION:Minion.BOMBER, Spawn.LANE:4},
					{Spawn.TIME:106, Spawn.MINION:Minion.HACKER, Spawn.LANE:2},
					{Spawn.TIME:106, Spawn.MINION:Minion.HACKER, Spawn.LANE:4},
					{Spawn.TIME:112, Spawn.MINION:Minion.TROOPER, Spawn.LANE:3},
					{Spawn.TIME:113, Spawn.MINION:Minion.BOMBER, Spawn.LANE:1},
					{Spawn.TIME:114, Spawn.MINION:Minion.BOMBER, Spawn.LANE:5},
					]
				},
				13: # I'm Blue Remix
				{
				Phase.GENERATE:true,
				Phase.DURATION:84,
				Phase.CANNON_COUNT:3,
				Phase.POWER_COUNT:7,
				Phase.INITIAL_TEXT:'Videogame',
				Phase.REPLICATE_TEXT:7,
				Phase.ARENA:0,
				Phase.SCRIPT:
					[
					{Spawn.TIME:1, Spawn.MINION:Minion.TANK, Spawn.LANE:1}, 
					]
				},
			}
			
func get_phase(value):
	return _phases[value]
