extends Node

enum Spawn{TIME, MINION, LANE}
enum Phase{GENERATE, CANNON_COUNT, POWER_COUNT, INITIAL_TEXT, REPLICATE_TEXT, ARENA, SCRIPT}
enum Minion{TROOPER, TANK, SPEEDER, HACKER, HACKERI}
enum Arena{BLUE, RED, PURPLE}
